org: "deisci"
pull_policy: "Always"
docker_tag: canary
# limits_cpu: "100m"
# limits_memory: "50Mi"

postgres:
  name: "database name"
  username: "database username"
  password: "database password"
  host: "database host"
  port: "database port"
