apiVersion: v1
kind: Secret
metadata:
  name: database-storage-keyfile
  labels:
    heritage: deis
  annotations:
    deis.io/objectstorage: "{{ .Values.global.storage }}"
type: Opaque
data: {{ if eq .Values.global.storage "gcs"}}
  key.json: {{.Values.gcs.key_json | b64enc}}
  database-bucket: {{.Values.gcs.database_bucket | b64enc }}{{ else if eq .Values.global.storage "azure"}}
  accountname: {{.Values.azure.accountname | b64enc }}
  accountkey: {{ .Values.azure.accountkey | b64enc }}
  database-container: {{ .Values.azure.database_container | b64enc }}{{ else if eq .Values.global.storage "s3"}}
  accesskey: {{ .Values.s3.accesskey | b64enc }}
  secretkey: {{ .Values.s3.secretkey | b64enc }}
  region: {{ .Values.s3.region | b64enc }}
  database-bucket: {{ .Values.s3.database_bucket | b64enc }}{{ else if eq .Values.global.storage "swift"}}
  username: {{ .swift.username | b64enc }}
  password: {{ .swift.password | b64enc }}
  authurl: {{ .swift.authurl | b64enc }}
  tenant: {{ .swift.tenant | b64enc }}
  authversion: {{ .swift.authversion | b64enc }}
  database-container: {{ .swift.database_container | b64enc }}{{else if eq .Values.global.storage "minio"}}
  accesskey: OFRaUlkySlJXTVBUNlVNWFI2STU=
  secretkey: Z2JzdHJPdm90TU1jZzJzTWZHVWhBNWE2RXQvRUk1QUx0SUhzb2JZaw=={{ end }}
